[package]
name = "lightning-router"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
once_cell = "1.21"

[build-dependencies]
cbindgen = "0.29"

[lib]
crate-type = ["staticlib"]
