[package]
name = "lightning-router-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
idevice = { path = "../../idevice/idevice", features = ["usbmuxd"] }
env_logger = { version = "0.11" }
